//----------------------------------------------//
// Gamelogic Grids                              //
// http://www.gamelogic.co.za                   //
// Copyright (c) 2013 Gamelogic (Pty) Ltd       //
//----------------------------------------------//

using Gamelogic.Extensions.Internal;

namespace Gamelogic.Grids
{
	/// <summary>
	/// All Shape Info classes should implement this interface.
	/// This provides basic transformations and set operations to combine
	/// shape info instances.
	/// </summary>
	[Version(1)]
	public interface IShapeInfo<TShapeInfo, TGrid, TPoint, TVectorPoint, TShapeOp>
		where TShapeInfo : IShapeInfo<TShapeInfo, TGrid, TPoint, TVectorPoint, TShapeOp>
		where TGrid : IGridSpace<TPoint>
		where TPoint : ISplicedVectorPoint<TPoint, TVectorPoint>, IGridPoint<TPoint>
		where TVectorPoint : IVectorPoint<TVectorPoint>
	{
		#region Set Operators

		/// <summary>
		/// Provides a shape operator that will form the intersection of the 
		/// shape describe by this instance and the shape info generated by one
		/// of the shape functions of the shape operator returned by this function.
		/// </summary>
		TShapeOp Intersection();

		/// <summary>
		/// Provides a shape operator that will form the union of the 
		/// shape describe by this instance and the shape info generated by one
		/// of the shape functions of the shape operator returned by this function.
		/// </summary>
		TShapeOp Union();

		/// <summary>
		/// Provides a shape operator that will form the difference of the 
		/// shape describe by this instance and the shape info generated by one
		/// of the shape functions of the shape operator returned by this function.
		/// </summary>
		TShapeOp Difference();

		#endregion

		#region Transforms

		TShapeInfo Translate(TVectorPoint offset);

		TShapeInfo Translate(int x, int y);

		#endregion

		#region EndShape

		/// <summary>
		/// This functions is called to end shape construction and returned 
		/// a grid described by this shape info.
		/// </summary>
		TGrid EndShape();

		#endregion
	}
}