namespace Gamelogic.Grids2.Graph
{
	/// <summary>
	/// A shape of a single cell at the origin.
	/// </summary>
	/// <seealso cref="Gamelogic.Grids2.Graph.PrimitiveShapeNode{Gamelogic.Grids2.GridPoint2}" />
	/// <autogeneratedoc />
	/// TODO Edit XML Comment Template for SingleShape2Node
	[ShapeNode("All/Single", 3)]
	public class SingleShape3Node : PrimitiveShapeNode<GridPoint3>
	{
		protected override IExplicitShape<GridPoint3> Generate()
		{
			return ExplicitShape.Single3();
		}
	}
}